# Introduction to Python : NumPy (multidimensional data arrays)

An introductory-to-Python notebook for the purposes of the course "Numerical Analysis" (Prof. Nikolaos Stergioulas) at Aristotle University of Thessaloniki (AUTh). 

A first version lives in [v1.0@2021](https://github.com/sfragkoul/Python_Intro) (based on "Introduction to Scientific Computing in Python" by Robert Johansson).

Notebook by Argyro Sasli, March 2022

## About NumPy

- [NumPy](https://numpy.org/) is a Python library (package) used for working with arrays. 


- **NumPy** stands for **Num**erical **Py**thon.


- It has functions for working in domain of linear algebra, fourier transform, and matrices.


- It offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.


- It is written partially in Python, but most of the parts that require fast computation are written in C or C++.


- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

### Why NumPy?

NumPy aims to provide an **array** object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ```ndarray```, it provides a lot of supporting functions that make working with ndarray very easy.

In [1]:
#NumPy is usually imported under the np alias
import numpy as np

## Creating NumPy arrays

There are a number of ways to initialize new numpy arrays, for example from

• a Python list or tuples

• using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.

• reading data from files

### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array

In [ ]:
arr = np.array(42)

print(arr)

### 1-D Arrays
1-D arrays, or vectors, can be created using a Python list or tuple

In [ ]:
# a vector: the argument to the array function is a Python list
vl = np.array([1,2,3,4]) # is a single dimensional array of 4 elements
print(vl,type(vl))
vl.shape

In [ ]:
# a vector: the argument to the array function is a Python tuple
vt = np.array((1, 2, 3, 4, 5))
print(vt)

### Higher Dimensional Arrays (N-D Arrays)

An array can have any number of dimensions.

#### 2-D Array

In [ ]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]]) #is a two - dimensional array which is composed of 3 single dimensional arrays
print(M,type(M))

**indexing**

In [ ]:
print('1st-row elements: ', M[0])

In [ ]:
print('2nd element on 1st row: ', M[0, 1])

**slicing**

In [ ]:
M[1,1:3]

In [ ]:
M[1][1:3] #remember the list slicing

In [ ]:
# a block from the original array
M[1:3, 1:3]

**strides**

In [ ]:
M[::2, ::2]

[Numpy shape() documentation](https://numpy.org/doc/stable/reference/generated/numpy.shape.html)

In [ ]:
M.shape # same as np.shape(M)

**dimensions**

In [ ]:
print('number of dimensions :', M.ndim)

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

In [ ]:
print('number of elements :', M.size)

**Why not simply use Python lists for computations instead of creating a new array type?**

• Python *lists* are very *general*. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplications, etc.

In [ ]:
print('the data type is :', M.dtype)

In [ ]:
#We get an error if we try to assign a value of the wrong type to an element in a numpy array
M[0,0] = "hello"

• NumPy arrays are **mutable** (creating immutbale arrays: [stackoverflow](https://stackoverflow.com/questions/5541324/immutable-numpy-array)) and memory efficient.

In [ ]:
M[0,0] = 10.0
print(M)

In [ ]:
# we can explicitly define the type of the array data when we create it, using the dtype keyword argument:
M = np.array([[1, 2], [3, 4]], dtype=complex)
print(M)

#We can also explicitly define the bit size of the data types, for example: int16, float64, complex128

### Generating arrays

```np.arange(start, stop, step)``` : The *last* element **is not** equal to the *stop* value

In [ ]:
x = np.arange(0, 10, 1) # arguments: start, stop, step
x
#x.shape

In [ ]:
x = np.arange(-1, 1, 0.1)
x

```np.linspace(start, stop, num)``` : Both end points are **included**

In [ ]:
# using linspace, *both end points ARE included*!!!
np.linspace(0, 10, 25) #(start, stop, num=50)

**Numbers spaced evenly on a log scale**

In [ ]:
np.logspace(0, 10, 10, base=np.e)

**mesh-grid**

In [ ]:
x, y = np.mgrid[0:5, 0:5]
x

In [ ]:
y

**Random** numbers

In [ ]:
from numpy import random

In [ ]:
# uniform random numbers in [0,1]
random.rand(5,5)

In [ ]:
# standard normal distributed random numbers
random.randn(5,5)

Array of given shape and type, **filled with zeros** 

In [ ]:
np.zeros((3,4))

Array of given shape and type, **filled with ones** 

In [ ]:
np.ones((3,3))

**Matrix MxN using for loops**

In [ ]:
A = np.array([[m+n*10 for n in range(5)] for m in range(4)])
A

#### Diagonal Matrix

In [ ]:
# a diagonal matrix
np.diag([1,2,3])

In [ ]:
# diagonal with offset from the main diagonal
np.diag([1,2,1], k=1)

In [ ]:
M=np.eye(6)
M

## Numpy's native file format

In [ ]:
np.save("eye-matrix.npy", M)

In [ ]:
np.load("eye-matrix.npy")

## Manipulating arrays

In [2]:
M = np.array([[1, 2], [3, 4], [5, 6]])
print(M)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Slicing works for rows and columns
M[1,:] = 0
M[:,1] = -1
M

In [3]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [ ]:
# Array slices are mutable: if they are assigned a new value the original array is modified
A[1:3] = [-2,-3]
A

**Append** values
```np.append(arr,values)```

In [4]:
np.append(A,6)

array([1, 2, 3, 4, 5, 6])

In [5]:
A

array([1, 2, 3, 4, 5])

In [7]:
B = np.append(A,[6,7,8])

**Delete** values ```np.delete(arr,obj)```

In [10]:
np.delete(B,B[-3:-1])

array([1, 2, 3, 4, 5, 6])

### NumPy Array Masking

A **masked array** is the combination of a standard ```numpy.ndarray``` and a *mask*. A **mask** is either *nomask*, indicating that no value of the associated array is invalid, or an <font color='red'>array of booleans</font> that determines for each element of the associated array <font color='red'> whether the value is valid or not </font>. 

- If the **index mask** is an NumPy array of data type *bool*, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element

In [ ]:
B = np.array([n for n in range(5)])
B

In [ ]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

In [ ]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

Someone can conditionally select elements from an array, using for example **comparison operators**

In [ ]:
x = np.arange(0, 10, 0.5)
x

In [ ]:
mask = (5 < x) * (x < 7.5)
mask

- **fancy indexing**: it means passing an array of indices to access multiple array elements at once

In [ ]:
x[mask] #fancy indexing

## Functions for extracting data from arrays and creating arrays

```Ruby
np.where(condition)
```

The *index mask* can be converted to *position index* using the ```where``` function

In [ ]:
indices = np.where(mask) #tells us where this is true
indices

In [ ]:
x[indices]

```Ruby
np.diag(array, k)
```
With the ```diag``` function we can also extract the diagonal (k=0 by default) and subdiagonals of an array

In [ ]:
A = np.array([[m+n*10 for n in range(5)] for m in range(5)]) # like before
A

In [ ]:
np.diag(A)

In [ ]:
np.diag(A, -2)

In [ ]:
np.diag(A, 1)

## Linear algebra

Vectorizing code is the key to writing eficient numerical calculation with Python/Numpy. That means
that as much as possible of a program should be formulated in terms of matrix and vector operations, like
matrix-matrix multiplication.

In [ ]:
#Scalar-array operations
v1 = np.arange(0, 5)
v2=v1 * 2

In [ ]:
A

**Transposed array**
```Ruby
array.T or np.transpose(array)
```
By defining an ```np.array```, the **attribute** ```.T``` (or ```np.transpose(array)```)gives the transposed of the array

In [ ]:
A.T

In [ ]:
np.transpose(A)

**Element-wise multiplication**

In [ ]:
A * A

In [ ]:
v1 * v1

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row

In [ ]:
A.shape, v1.shape

In [ ]:
A * v1

**Matrix Mutiplication**

In [ ]:
np.dot(A, A)

In [ ]:
np.dot(A, v1)

### Matrix function
```Ruby
np.matrix(array)
```
Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that **retains its 2-D nature through operations**. It has certain special operators, such as <font color='green'> * (matrix multiplication)</font> and <font color='green'> ** (matrix power)</font>.

In [ ]:
M = np.matrix(A)
v = np.matrix(v1)
v.shape

Be aware of incomplatible shapes!!! If we try to add, subtract or multiply objects with incomplatible shapes we get an error

In [ ]:
M * v

In [ ]:
v = v.T # make it a column vector
v.shape

## Data processing

First, import the function ```genfromtxt()```
```Python
from numpy import genfromtxt
```

**Arguments**:

* fname: The file name (required argument)


* delimiter: The string used to separate values. By default, any consecutive whitespaces act as delimiter. (Optional)


* skip_header: The number of lines to skip at the beginning of the file. (Optional)

In [ ]:
from numpy import genfromtxt
data = genfromtxt('sample_data/eosSLy4.txt', delimiter=' ', skip_header=1)

In [ ]:
data.shape

```np.mean()```

In [ ]:
np.mean(data[0,:])

In [ ]:
#mean per row
np.mean(data,axis=1)

In [ ]:
#mean per column
np.mean(data,axis=0)

In [ ]:
print(data[1,:].max())
print(data[1,:].min())

## Reshaping, resizing and stacking arrays

The shape of an NumPy array can be modified without copying the underlaying data, which makes it a *fast
operation even for large arrays*.

In [ ]:
A = np.array([[m+n*10 for n in range(5)] for m in range(5)])
A

In [ ]:
n, m = A.shape
n,m

- ```reshape()```

In [ ]:
B = A.reshape((1,n*m))
B

In [ ]:
A

Changing an element of B array affects A array! ```B=A.reshape((1,n*m))``` is only a different view of the same data!

In [ ]:
B[0,0:5] = 5 # modify the array

In [ ]:
A

```flatten()```

The function flatten makes a higher-dimensional array into a vector. But this function **creates a copy of the data**.

In [ ]:
C = A.flatten()
C

In [ ]:
C[0:5] = 10
C

In [ ]:
A

### Adding a new dimension: newaxis

With **newaxis**, we can insert new dimensions in an array, for example converting a vector to a column or
row matrix

In [ ]:
v = np.array([1,2,3])
np.shape(v) #1-D array

In [ ]:
# make a column matrix of the vector v
v[:, np.newaxis]

In [ ]:
# column matrix
v[:,np.newaxis].shape

In [ ]:
# row matrix
print(v[np.newaxis,:])
print('Its shape is:', v[np.newaxis,:].shape)
print('The above has', v[np.newaxis,:].shape[0],'row(s) and', v[np.newaxis,:].shape[1],'column(s)')

### Stacking and repeating arrays

In [ ]:
a = np.array([[1, 2], [3, 4]])
a
a.shape

**Repeating elements**

```np.repeat(array,n)``` : repeat each element of the array n times

In [ ]:
np.repeat(a, 3)

```np.tile(A,n)``` : construct an array by repeating A the number of times given by n

In [ ]:
np.tile(a, 3)

**concatenate**

```np.concatenate((a, b, c, ....), axis=0)```: join a sequence of arrays along an existing axis.

In [ ]:
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b.T), axis=1)

```np.vstack((a,b))``` : same as ```np.concatenate((a, b), axis=0)```

In [ ]:
np.vstack((a,b))

```np.hstack((a,b))``` : same as ```np.concatenate((a, b), axis=1)```

In [ ]:
np.hstack((a,b.T))

### Copy and deep copy

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is
important for example when objects are passed between functions, to avoid an excessive amount of memory
copying when it is not necessary (technical term: pass by reference).

In [ ]:
A = np.array([[1, 2], [3, 4]])
A

In [ ]:
# now B is referring to the same array data as A
B = A
B

In [ ]:
# changing B affects A
B[0,0] = 10
B

In [ ]:
A

If we want to avoid this behavior, so that when we get a new completely independent object B copied
from A, then we need to do a so-called "deep copy" using the function **copy**

In [ ]:
D = np.copy(A)
D

In [ ]:
# now, if we modify B, A is not affected
D[0,0] = -5
D

In [ ]:
A

## Iterating over array elements

In [ ]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

When we need to iterate over each element of an array and modify its elements, it is convenient to use
the **enumerate** function to obtain both the element and its index in the for loop

In [ ]:
grocery = ['bread', 'milk', 'butter']
enumerateGrocery = enumerate(grocery)

print(type(enumerateGrocery))

# converting to list
print(list(enumerateGrocery))

In [ ]:
# changing the default counter
enumerateGrocery = enumerate(grocery, 10)
print(list(enumerateGrocery))

When we need to iterate over each element of an array and modify its elements, it is convenient to use
the enumerate function to obtain both the element and its index in the for loop

In [ ]:
M = np.array([[ 0, 4], [ 9, 16]])

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

In [ ]:
M

## Using arrays in conditions

When using arrays in conditions,for example if statements and other boolean expressions, one needs to use
```any``` or ```all```, which requires that any or all elements in the array evalutes to True

In [ ]:
M = np.array([[ 0, 4], [ 9, 16]])

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")